version: '3.1'
services:
   web:
      container_name: web
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 8000:8000
      volumes:
         - .:/code
      restart: always
